version: '3'
services:
  postgres:
    image: postgres:9.6.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=
    volumes:
      - ./tmp/db/pg_data:/var/lib/postgresql/data

  redis:
    image: redis:2.8.23
    ports:
      - "6379:6379"
    volumes:
      - ./tmp/db/redis_data:/data
    entrypoint: redis-server --appendonly yes
